spring:
  datasource:
    url: jdbc:mysql://mysql:3306/drone_delivery?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: drone_user
    password: drone_password

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false

logging:
  level:
    backend.databaseproject: info
    org.hibernate.SQL: info
